### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by Costava** [Costava/broken-bounty#5]
1. Clone the repo
2. `npm install`
3. `npm run build-dev`

The build fails with error:

```
> broken-bounty@1.0.1 build-dev /home/user/Desktop/broken-bounty
> gulp clear-build && gulp dev-tasks && gulp embed && gulp html-dev

fs.js:41
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:41:5
    at req_ (/home/user/Desktop/broken-bounty/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/user/Desktop/broken-bounty/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/user/Desktop/broken-bounty/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! broken-bounty@1.0.1 build-dev: `gulp clear-build && gulp dev-tasks && gulp embed && gulp html-dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the broken-bounty@1.0.1 build-dev script.
```

Dependencies may need to be updated.

**Comment by adityaarakeri** [comment]
assign this to me, will take a look.

**Comment by Costava** [comment]
> assign this to me, will take a look.

I assigned the issue to you @adityaarakeri :+1:
